version: '3'
services:
  postgres:
    image: qnib/plain-postgres:local
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_PASSWORD=password
  clair:
    image: qnib/plain-clair
    environment:
      - CLAIR_DB_HOST=clair_postgres
    ports:
      - "6060:6060"
      - "6061:6061"
    deploy:
      restart_policy:
        condition: on-failure
